name: conda
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download and install conda
      run: |
       wget https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh
       chmod u+x Anaconda3-2021.05-Linux-x86_64.sh
       bash -y Anaconda3-2021.05-Linux-x86_64.sh
            
    - name: activate base
      run: |
       conda activate base
