name: dep_sandbox
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          sandbox:
            - 'sandbox/**'

    # run only if 'sandbox' files were changed
    - name: sandbox tests
      if: steps.filter.outputs.sandbox == 'true'
      run: |
        pytest sandbox
